/* Generated By:JavaCC: Do not edit this line. CCJSqlParserVisitor.java Version 7.0.3 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=1b7854aec7e4c1cb146cbffb9d4b3ba9 (do not edit this line) */
