/* Generated By:JavaCC: Do not edit this line. CCJSqlParserTreeConstants.java Version 7.0.3 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTVOID = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTCOLUMN = 3;
  public int JJTTABLE = 4;
  public int JJTPLAINSELECT = 5;
  public int JJTSETOPERATIONLIST = 6;
  public int JJTWITHITEM = 7;
  public int JJTSELECTITEM = 8;
  public int JJTJOINEREXPRESSION = 9;
  public int JJTLIMITWITHOFFSET = 10;
  public int JJTPLAINLIMIT = 11;
  public int JJTEXPRESSION = 12;
  public int JJTREGULARCONDITION = 13;
  public int JJTLIKEEXPRESSION = 14;
  public int JJTPRIMARYEXPRESSION = 15;
  public int JJTCASEWHENEXPRESSION = 16;
  public int JJTFUNCTION = 17;
  public int JJTSUBSELECT = 18;


  public String[] jjtNodeName = {
    "Statement",
    "void",
    "Statements",
    "Column",
    "Table",
    "PlainSelect",
    "SetOperationList",
    "WithItem",
    "SelectItem",
    "JoinerExpression",
    "LimitWithOffset",
    "PlainLimit",
    "Expression",
    "RegularCondition",
    "LikeExpression",
    "PrimaryExpression",
    "CaseWhenExpression",
    "Function",
    "SubSelect",
  };
}
/* JavaCC - OriginalChecksum=6a303f94c0bca6a2b59ee54e22a1d665 (do not edit this line) */
